kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: slave
networking:
  ipFamily: dual
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443
        hostPort: 7443
        protocol: TCP
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
