apiVersion: v1
kind: Namespace
metadata:
  name: fleet-local

---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fleet-local
  namespace: fleet-local
spec:
  repo: https://github.com/nusnewob/local.nusnewob.dev.git
  branch: main
  paths:
    - fleet/workspaces/local
  targets:
    - name: all
      clusterSelector: {}

---
apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterRegistrationToken
metadata:
  name: fleet-local
  namespace: fleet-local
spec:
  ttl: 0h
