{{- range .Values.providerConfig }}
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .name }}
spec:
  credentials:
{{ toYaml .credentials | indent 4 }}

---
{{- end }}
