{{- range .Values.providers }}
{{- if .rbac }}
{{- if .rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}
subjects:
  - kind: ServiceAccount
    name: {{ .name }}
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
{{- end }}
{{- end }}
{{- end }}
